[package]
name = "socketcan-isotp"
version = "0.1.0"
authors = ["marcelbuesing <buesing.marcel@googlemail.com>"]
edition = "2018"
license = "BSD-3-Clause"

[dependencies]
bitflags = "1.2"
libc = "0.2"
nix = "0.16"
