on: [push, pull_request]

name: CI

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: beta
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: beta
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: beta
          override: true
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  license-check:
    name: license-check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: download cargo-deny
      shell: bash
      env:
        DVS: 0.3.0-beta
        DREPO: EmbarkStudios/cargo-deny
        TARGET: x86_64-unknown-linux-musl
      run: |
        temp_archive=$(mktemp --suffix=.tar.gz)
        curl -L --output "$temp_archive" https://github.com/$DREPO/releases/download/$DVS/cargo-deny-$DVS-$TARGET.tar.gz
        tar -xzvf "$temp_archive" -C . --strip-components=1 --wildcards "*/cargo-deny"
    - name: cargo-deny check licenses
      run: ./cargo-deny -L debug check license
    - name: cargo-deny check bans
      run: ./cargo-deny -L debug check ban
